contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('',views.index, name='index'),
    path('search/',views.search, name='search'),

    # contact (CRUD)
    path('contact/<int:contact_id>/',views.contact, name='contact'),
    path('contact/create/',views.create, name='create'),
    path('contact/<int:contact_id>/update/',views.update, name='update'),
    path('contact/<int:contact_id>/delete/',views.delete, name='delete'),


    #user
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_form, name='login'),
    path('user/logout/', views.logout_view, name='logout')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now())
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    pictures = models.ImageField(blank=True, upload_to="pictures/%Y/%m")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE,
        blank=True, null=True
        ) 
    owner = models.ForeignKey(User,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

contact/forms.py
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, ValidationError
from django import forms

class ContactForm(ModelForm):
    pictures = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*'
            }
        )
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Digite o primeiro nome',
            
        }),
        label='Primeiro Nome',
        help_text='Digite o Primeiro Nome'
    )
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)

       
    class Meta:
        model = models.Contact
        fields = 'first_name',"last_name", "phone", 'email', 'description', 'category','pictures',
      

    def clean(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        msg = ValidationError('Primeiro nome não pode ser igual ao segundo nome', code='invalid')
        if first_name == last_name:
            self.add_error('first_name',msg)
            self.add_error('last_name',msg)
       

        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not str(first_name).isalpha():
            self.add_error(
                'first_name',
                ValidationError(
                    'Digite apenas Letras',
                    code='invalid'
                )
            )
        if len(str(first_name)) < 2:
            self.add_error(
                'first_name',
                ValidationError(
                    'Não existe nome com apenas uma letra!',
                    code='invalid'
                )
            )

        
        return first_name

class RegisterUser(UserCreationForm):
    class Meta:
        first_name = forms.CharField(
            required=True
        )
        last_name = forms.CharField(
            required=True
        )
        email = forms.EmailField(
            required=True
        )
        
        model = User
        fields = 'first_name','last_name','email','username','password1','password2'
        

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError(
                    'Esse email já existe',
                    code='invalid'
                )
            )
        return email 
     

contact/views/contact_details.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.core.paginator import Paginator
from contact.models import Contact
def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    paginator = Paginator(contacts, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'site_title': 'Contato - ',
    }

    return render(
        request,
        'contact/index.html',
        context
    )



def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)

    site_title = f'{single_contact.first_name} {single_contact.last_name} -'
    context = {
        'contact': single_contact,
        'site_title': site_title,
    }

    return render(request,
        'contact/contact.html',
        context
    )



def search(request):
    search_value = request.GET.get("q", "").strip()
    print(search_value)
    if search_value == '':
        return redirect("contact:index")
    
    
    contacts = Contact.objects.filter(show=True)\
            .filter(
                    Q(first_name__icontains=search_value) |
                    Q(last_name__icontains=search_value) |
                    Q(phone__icontains=search_value) |
                    Q(email__icontains=search_value))\
            .order_by('-id')
            
    paginator = Paginator(contacts, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    print(contacts.query)
    context = {
        'page_obj': page_obj,
        'site_title': 'Search -',
    }
    return render(
            request,
            'contact/index.html',
            context
    )

contact/views/contact_forms.py
from django.shortcuts import render,redirect, get_object_or_404
from contact.forms import ContactForm
from django.urls import reverse
from . import Contact

def create(request):
    form_action = reverse("contact:create")
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.id)
    
        return render(
            request,
            'contact/create.html',
            context
        )
    
    
    
    
    context = {
        
        'form': ContactForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )

def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    form_action = reverse("contact:update", args=(contact_id,))
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES,instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)
    
        return render(
            request,
            'contact/create.html',
            context
        )
    
    
    
    
    context = {
        
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )

def delete(request, contact_id):
    contact =get_object_or_404(Contact, pk=contact_id, show=True)
    confirmation = request.POST.get('confirmation', 'no')
    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.core.paginator import Paginator
from contact.models import Contact
def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    paginator = Paginator(contacts, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'site_title': 'Contato - ',
    }

    return render(
        request,
        'contact/index.html',
        context
    )



def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)

    site_title = f'{single_contact.first_name} {single_contact.last_name} -'
    context = {
        'contact': single_contact,
        'site_title': site_title,
    }

    return render(request,
        'contact/contact.html',
        context
    )



def search(request):
    search_value = request.GET.get("q", "").strip()
    print(search_value)
    if search_value == '':
        return redirect("contact:index")
    
    
    contacts = Contact.objects.filter(show=True)\
            .filter(
                    Q(first_name__icontains=search_value) |
                    Q(last_name__icontains=search_value) |
                    Q(phone__icontains=search_value) |
                    Q(email__icontains=search_value))\
            .order_by('-id')
            
    paginator = Paginator(contacts, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    print(contacts.query)
    context = {
        'page_obj': page_obj,
        'site_title': 'Search -',
    }
    return render(
            request,
            'contact/index.html',
            context
    )

contact/views/user_forms.py
from django.shortcuts import render
from contact.forms import RegisterUser
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib import messages
from django.shortcuts import redirect



def register(request):
    form = RegisterUser()

    if request.method == 'POST':
        form = RegisterUser(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,"Conta Criada com Sucesso!")
            return redirect('contact:login')
            
    return render(
        request,
        'contact/register.html',
        {
            'form': form,
        }
    )


def login_form(request):
    form =  AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request,user)
            messages.success(request,"User Autenticado com sucesso!")
            return redirect('contact:index')

    return render(
        request,
        'contact/login.html',
        {
            'form': form,
            'title': '',
        }
        )


def logout_view(request):
    auth.logout(request)
    messages.info(request, "Você fez logout com sucesso!")
    return redirect('contact:login')

contact/templates/contact/contact.html
{% extends "global/base.html" %}



{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>
        <p><b>ID: </b>{{contact.id}}</p>
        <p><b>Email: </b>{{contact.email}}</p>
        <p><b>Phone: </b>{{contact.phone}}</p>
        <p><b>Create Date: </b>{{contact.created_date}}</p>
        <p><b>Description: </b>{{contact.description}}</p>
        <p><b>Category: </b>{{contact.category.name}}</p>
        {% if contact.pictures %}
            <img src="{{contact.pictures.url}}" alt="{{contact.first_name}} {{contact.last_name}}"></img>
        {% endif %}
        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>
            <form action="{% url 'contact:delete' contact.id %}" method='POST'>
                {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type='hidden' name='confirmation' value='yes'>
                    <button class="btn btn-link btn-delete" type='submit' >Confirma?</button>
                {% else %}
                    <button class="btn btn-link btn-delete" type='submit' >Delete</button>
                
                {% endif %}
            </form>
        </div>
    </div>

    {% endblock content %}

contact/templates/contact/create.html
{%extends "global/base.html"%}


{%block content%} 
    <div clasd="form-wrapper">
        <h2>Contact</h2>
        <form
            action="{{form_action}}"
            method="POST"
            enctype="multipart/form-data"
        >
            {% csrf_token %}
            {% for field in form %}
                <div class="form-content">
                    <div class="form-group">
                        <label for="{{field.id_for_name}}">{{field.label}}</label>
                        {{field}}
                        {{field.errors}}
                        {% if field.help_text %}
                            <p class='help-text'>{{field.help_text}}</p>
                        {% endif %}
                    </div>
                    {% if field.name == 'pictures' and field.value.url %}
                        <div class="form-group">
                            <img src="{{field.value.url}}" alt="">
                        </div>
                    {% endif %}
            {% endfor %}
            </div>
            {% if form.non_field_errors %}
                    <div class="form-content">
                        <div class="form-group">
                            <div class="message error">
                            {{form.non_field_errors}}
                            </div>
                        </div>
                    </div>
            {% endif %}

            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Send</button>
                </div>
            </div>
        </form>



    </div>
{%endblock content%}

contact/templates/contact/index.html
{% extends "global/base.html" %}


{% block content %}
{%if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First Name</th>
                    <th class="table-header">Last Name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">Email</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in page_obj %}
                <tr class="table-row">
                        <td class="table-cell">
                            <a class="table-link" href="{% url "contact:contact" contact.id%}">
                                {{contact.id}}
                            </a>
                        </td>
                        <td class="table-cell">
                                {{contact.first_name}}
                        </td>
                        <td class="table-cell">
                                {{contact.last_name}}
                            
                        </td>
                        <td class="table-cell">
                                {{contact.phone}}
                        </td>
                        <td class="table-cell">
                                {{contact.email}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {%else%}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum Contato Encontrado
        </h1>
    </div>
{%endif%}
{% endblock content %}

contact/templates/contact/login.html
{% comment %}
    Arquivo utilizado para usuario se autenticar no site.
{% endcomment %}

{# Extendendo arquivo Principal#}
{%extends "global/base.html"%}


{%block content%} 
    <div class="form-wrapper">
        {% if not user.is_authenticated %}
            <h2>Login</h2>
            {#  Mensagem de info quando o user fizer logout #}
            {{message}}
        {% include "contact/partials/_user-form.html" %}

        {% endif %}
        {% if user.is_authenticated %}
        <h2>{{title}}</h2>
        {# Mensagem de sucess quando o user se autenticar com sucesso! #}
        <p>{{message}}</p>
        <p>Você fez login como {{user.username}}</p>
        <p>Clicka <a href="{% url "contact:logout" %}">aqui</a> para sair.</p>

        {% endif %}


{%endblock content%}

contact/templates/contact/register.html
{%extends "global/base.html"%}


{%block content%} 
    <div clasd="form-wrapper">
        <h2>Register</h2>
        {% include "contact/partials/_user-form.html" %}
{%endblock content%}